/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        CustomSwitch: typeof import('./src/components/CustomSwitch.vue')['default']
        CustomUIDInput: typeof import('./src/components/CustomUIDInput.vue')['default']
        DialogListItem: typeof import('./src/components/DialogListItem.vue')['default']
        ElCarousel: typeof import('element-plus/es')['ElCarousel']
        ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
        ElDropdown: typeof import('element-plus/es')['ElDropdown']
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
        LauncherBanner: typeof import('./src/components/LauncherBanner.vue')['default']
        LauncherPosts: typeof import('./src/components/LauncherPosts.vue')['default']
        LoadFailedBlock: typeof import('./src/components/LoadFailedBlock.vue')['default']
        LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
        MyCheckbox: typeof import('./src/components/MyCheckbox.vue')['default']
        MyTabs: typeof import('./src/components/MyTabs.vue')['default']
        MyTag: typeof import('./src/components/MyTag.vue')['default']
        MyTooltip: typeof import('./src/components/MyTooltip.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        ScrollWrapper: typeof import('./src/components/ScrollWrapper.vue')['default']
        StatIcon: typeof import('./src/components/StatIcon.vue')['default']
        TemplateDialog: typeof import('./src/components/TemplateDialog.vue')['default']
        TopHeader: typeof import('./src/components/TopHeader.vue')['default']
        UpdateDialogContent: typeof import('./src/components/UpdateDialogContent.vue')['default']
    }
}
